# Generated by Django 3.1.6 on 2021-02-25 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.TextField()),
                ('total_likes', models.PositiveIntegerField()),
                ('comments', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('fav_movies', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('photo_url', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('members', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('website_url', models.URLField()),
                ('creator_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society_app.people')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=50)),
                ('event_title', models.CharField(max_length=50)),
                ('creator_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society_app.people')),
            ],
        ),
    ]
